(ns hiccup-clj-lsp.html)

(def global-attributes [:accesskey :class :contenteditable :data- :dir :draggable :hidden :id :lang :onblur :onchange :onclick :oncontextmenu :oncopy :oncut :ondblclick :ondrag :ondragend :ondragenter :ondragleave :ondragover :ondragstart :ondrop :onfocus :oninput :oninvalid :onkeydown :onkeypress :onkeyup :onmousedown :onmousemove :onmouseout :onmouseover :onmouseup :onmousewheel :onpaste :onscroll :onselect :onwheel :spellcheck :style :tabindex :title :translate])

(def ^:private incomplete-html-elements
  {:a [:download :href :hreflang :media :rel :target :type]
   :abbr []
   :acronym []
   :address []
   :applet []
   :area [:alt :coords :download :href :hreflang :media :rel :shape :target]
   :article []
   :aside []
   :audio [:autoplay :controls :loop :muted :onabort :oncanplay :oncanplaythrough :ondurationchange :onemptied :onended :onerror :onloadeddata :onloadedmetadata :onloadstart :onpause :onplay :onplaying :onprogress :onratechange :onseeked :onseeking :onstalled :onsuspend :ontimeupdate :onvolumechange :onwaiting :preload :src]
   :b []
   :base [:href :target]
   :basefont []
   :bdi []
   :bdo []
   :big []
   :blockquote [:cite]
   :body [:onafterprint :onbeforeprint :onbeforeunload :onerror :onhashchange :onload :onoffline :ononline :onpagehide :onpageshow :onpopstate :onresize :onstorage :onunload]
   :br []
   :button [:autofocus :disabled :form :formaction :name :type :value]
   :canvas [:height :width]
   :caption []
   :center []
   :cite []
   :code []
   :col [:span]
   :colgroup [:span]
   :data []
   :datalist []
   :dd []
   :del [:cite :datetime]
   :details [:ontoggle :open]
   :dfn []
   :dialog []
   :dir []
   :div []
   :dl []
   :dt []
   :em []
   :embed [:height :onabort :oncanplay :onerror :src :type :width]
   :fieldset [:disabled :form :name]
   :figcaption []
   :figure []
   :font []
   :footer []
   :form [:accept-charset :action :autocomplete :enctype :method :name :novalidate :onreset :onsubmit :rel :target]
   :frame []
   :frameset []
   :h1 []
   :h2 []
   :h3 []
   :h4 []
   :h5 []
   :h6 []
   :head []
   :header []
   :hr []
   :html []
   :i []
   :iframe [:height :name :onload :sandbox :src :srcdoc :width]
   :img [:alt :height :ismap :onabort :onerror :onload :sizes :src :srcset :usemap :width]
   :input [:accept :alt :autocomplete :autofocus :checked :dirname :disabled :form :formaction :height :list :max :maxlength :min :multiple :onload :onsearch :pattern :placeholder :readonly :required :size :src :step :type :value :width]
   :ins [:cite :datetime]
   :kbd []
   :label [:for :form]
   :legend []
   :li [:value]
   :link [:href :hreflang :media :onload :rel :sizes :type]
   :main []
   :map [:name]
   :mark []
   :meta [:charset :content :http-equiv :name]
   :meter [:form :high :low :max :min :optimum :value]
   :nav []
   :noframes []
   :noscript []
   :object [:data :form :height :name :onabort :oncanplay :onerror :type :usemap :width]
   :ol [:reversed :start]
   :optgroup [:disabled :label]
   :option [:disabled :label :selected :value]
   :output [:for :form :name]
   :p []
   :param [:name :value]
   :picture []
   :pre []
   :progress [:max :value]
   :q [:cite]
   :rp []
   :rt []
   :ruby []
   :s []
   :samp []
   :script [:async :charset :defer :onerror :onload :src :type]
   :section []
   :select [:autofocus :disabled :form :multiple :name :required :size]
   :small []
   :source [:media :sizes :src :srcset :type]
   :span []
   :strike []
   :strong []
   :style [:media :onerror :onload :type]
   :sub []
   :summary []
   :sup []
   :svg []
   :table []
   :tbody []
   :td [:colspan :headers :rowspan]
   :template []
   :textarea [:autofocus :cols :dirname :disabled :form :maxlength :name :placeholder :readonly :required :rows :wrap]
   :tfoot []
   :th [:colspan :headers :rowspan :scope]
   :thead []
   :time [:datetime]
   :title []
   :tr []
   :track [:default :kind :label :oncuechange :src :srclang]
   :tt []
   :u []
   :ul []
   :var []
   :video [:autoplay :controls :height :loop :muted :onabort :oncanplay :oncanplaythrough :ondurationchange :onemptied :onended :onerror :onloadeddata :onloadedmetadata :onloadstart :onpause :onplay :onplaying :onprogress :onratechange :onseeked :onseeking :onstalled :onsuspend :ontimeupdate :onvolumechange :onwaiting :poster :preload :src :width]
   :wbr []})

(def html-elements
  (update-vals incomplete-html-elements (fn [v] (conj v global-attributes))))
